//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursesApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_trainee
    {
        public int course_trainee_trainee_id { get; set; }
        public int course_trainee_course_id { get; set; }
        public System.DateTime course_trainee_registration_date { get; set; }
    
        public virtual course course { get; set; }
        public virtual course_trainee course_trainee1 { get; set; }
        public virtual course_trainee course_trainee2 { get; set; }
    }
}
