//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursesApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoursesDBEntities : DbContext
    {
        public CoursesDBEntities()
            : base("name=CoursesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<course_lessons> course_lessons { get; set; }
        public virtual DbSet<course_trainee> course_trainee { get; set; }
        public virtual DbSet<trainee> trainees { get; set; }
        public virtual DbSet<trainer> trainers { get; set; }
    }
}
