//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursesApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course()
        {
            this.course_trainee = new HashSet<course_trainee>();
        }
    
        public int course_id { get; set; }
        public string course_name { get; set; }
        public System.DateTime course_creation_date { get; set; }
        public int course_ctg_id { get; set; }
        public Nullable<int> course_trainer_id { get; set; }
        public string course_description { get; set; }
    
        public virtual category category { get; set; }
        public virtual course_lessons course_lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_trainee> course_trainee { get; set; }
        public virtual trainer trainer { get; set; }
    }
}
