//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursesApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainee
    {
        public int trainee_id { get; set; }
        public string trainee_name { get; set; }
        public string trainee_email { get; set; }
        public string trainee_password { get; set; }
        public System.DateTime trainee_creation_date { get; set; }
        public Nullable<bool> trainee_is_active { get; set; }
    }
}
